GET http://localhost:3000/todos/

###

GET http://localhost:3000/todos/?category=ravindra

###

GET http://localhost:3000/todos/5/

###
GET http://localhost:3000/agenda/?date=2021-2-22

###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "Ravindra",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-2-22"
}

###

PUT http://localhost:3000/todos/5/
Content-Type: application/json

{
    "dueDate":"2021-2-22"
}