
GET http://localhost:3000/todos/

###
GET http://localhost:3000/todos/?category=HOME

###
GET http://localhost:3000/todos/4/

###

GET http://localhost:3000/agenda/?date=2021-3-1

###

POST http://localhost:3000/todos/
Content-Type: application/json

{
  "id": 6,
  "todo": "Finalize event theme",
  "priority": "LOW",
  "status": "TO DO",
  "category": "HOME",
  "dueDate": "2021-02-22"
}
###
PUT http://localhost:3000/todos/5/
Content-Type: application/json

{
  "dueDate": "2021-01-12"
}

###
DELETE http://localhost:3000/todos/6/
